server:
  port: 8040

spring:
  data:
    mongodb:
      uri: mongodb://mongo:123@localhost:27017/notification?authSource=admin
  kafka:
    consumer:
      bootstrap-servers: localhost:9092

      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: Success:com.example.notification.dto.PaymentSuccessDTO,Complete:com.example.notification.dto.ShipmentSuccess


eureka:
  instance:
    hostname: localhost