jwt:
  auth:
    converter:
      resource-id: demo-for-keyclock
      principle-attribute: preferred_username

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:8280/realms/demo"
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: gateway-service